### ISSUE TITLE
Hotkey is grabbed even when disabled

### ISSUE THREAD

**Issue by eddy-geek** [negesti/gnome-shell-extensions-negesti#93]
This occurs at least for "Move to right screen" hotkey: even if the "Enabled" box is unchecked in "Keyboard Shortcuts" preferences panel, the default hotkey (Shift+Super+Right) is still grabbed, disabling gnome's "Move to next screen" hotkey if oconfigured to the same combination.

Workaround is to change to anything else e.g. Shift+Alt+Super+Right

**Comment by negesti** [comment]
I'm unabel to reproduce this. Are your running an up to date version of gnome-shell and the extension?
You could try to restart the shell (alt+f2 - r) and check if the keybinding is removed/not added after a restart.

**Comment by eddy-geek** [comment]
I can confirm that even after multiple restarts issue persists. I can reproduce by changing the hotkey back to Shift+Super+Right even without toggling the "enabled" checkbox

Also it seems that there is no way set an emtpy hotkey (unlike gnome-shell hotkey editor where pressing Backspace key does the trick.

**Comment by eddy-geek** [comment]
I can confirm that even after multiple restarts issue persists. I can reproduce by changing the hotkey back to Shift+Super+Right even without toggling the "enabled" checkbox

Also it seems that there is no way set an emtpy hotkey (unlike gnome-shell hotkey editor where pressing Backspace key does the trick.

**Comment by negesti** [comment]
i was not able to add validation to the UI that allowed empty keys and worked correct. That's why i added the enable/disable checkboxes to all settings. Just setting it to an empty hotkey would be easier and more gnome like. Unfortunately i don't have enough time atm. 

The settings are stored in dconf `/org/gnome/shell/extensions/org-lab21-putwindow/`. Can you check please, if the keybinding for "Move to right screen" is disabled in dconf settings properly. e.g. run 

` dconf read  /org/gnome/shell/extensions/org-lab21-putwindow/put-to-right-screen-enabled`

or open dconf-editor and navigate to the folder. The settings is immediately updated after changing it in PutWindow config window.

**Comment by negesti** [comment]
@eddy-geek i need the stored settings to fix this

**Comment by negesti** [comment]
have you tried this with the current version? the keybinding can be disabled using the backspace now. Please reopen the issue if it still exists
