### ISSUE TITLE
Multiple monitors issue

### ISSUE THREAD

**Issue by Pithikos** [negesti/gnome-shell-extensions-negesti#94]
I am using Gnome3 with Ubuntu15 and although I love this extension there is something that makes it unusable for me both at work and home.

I have a multiple monitor setup in both cases. If I open a window in the middle monitor and try to move it to the right (CTRL+9) it will move to the right of my left monitor. This makes it quite frustrating.

Would appreciate some feedback on this issue since the extension itself is super handy.. if I actually got it to work properly.

Thanks

**Comment by negesti** [comment]
hm, maybe disabling "Always use multiple widths/heights".

read it again. you have 3 monitors in horizontal setup and if you move a window that is on the middle monitor, it is moved to the left/right?

The current monitor is defined be the top left edge of the window. If your window is 1px on the left monitor, the extension uses the first monitor

**Comment by negesti** [comment]
still using the extension or can i close this?

**Comment by Pithikos** [comment]
Thanks for your reply. I do use it but it is still a bit of an annoyance. I use it with your proposed method but I need to combine it with other scripts and tools in order to maximize the window once I moved it across a different monitor :/

**Comment by negesti** [comment]
let me guess, you have a extension to hide the top bar on your primary screen?

**Comment by ppaarraaddooxx** [comment]
I'm also using triple monitor setup, and I'm using the current github version, and the problem still exists. The problem does indeed stem from the interaction with "Hide Top bar". I have the Top Bar on my middle/primary screen. I believe it has to do with the options in the section "Intellihide", specifically "Only hide panel when a window takes the space". 

With that active, and as long as there is no window covering the Top Bar (so the Top Bar is visible), that is when the problems start happening. The moment you reposition a window that ends up on the middle screen and covering the Top Bar, the top bar will disappear, and after that a move to the left screen fails. But if you do a next move right after that changes that window again, say tile left for example, the window jumps to the left screen with the last move done aswell.

Another example is a "right tiled" window on the left screen, you move it to the middle screen, then try to move another right screen. Instead of the 2nd move moving it to the right screen, it actually stays on your middle screen, but fully maximizes.

A by product is as well: When you open a window on screen with Top Bar, and you want to move it to top left / top / top right. It should ignore the Top Bar pixel settings, since it would auto move away if you put a window on top of a bar. However, Put Extension does count the Top Bar as "Solid" and puts the window below it without overlapping. This is of course not the behavior you want.

I'm sure there are some more weird interactions to be found. But, simple workaround: Don't turn on "Only hide panel when a window take the place". It is a nice feature, but I installed Hide Top Bar to save space, so having it always hidden is not an issue.

I figure a fix for your could would be to simply work out if the addon Hide Top Bar is running, and if it is fully ignore the pixels of the Top Bar, because if you place a window on top of the bar it will hide anyways. That should be the correct interaction. Your code shouldn't start trying to figure out if the top bar is shown or not, and adjust your placement, this is incorrect.

**Comment by Pithikos** [comment]
An update: I did indeed use the addon that removes the top bar (Maximus something). I did remove that from my work computer and still the same behaviour. The weird thing is that on a new restart everything works fine. It's just after a while once opened a few windows here and there that the bug occurs.

**Comment by negesti** [comment]
All extensions that hide the top bar work different and it's not that easy to check if it is currently visible or not. For the maximus extension it looks like i also updates the usable screen size, but that's just a guess.
currently i don't have the time to work on this issue sry

**Comment by Pithikos** [comment]
negesti, that's understandable. I think it's worth keeping the issue open though just as a reminder and in case someone manages to solve/provide more info on the issue.

**Comment by GabLeRoux** [comment]
Maybe using [Accerciser](https://wiki.gnome.org/action/show/Apps/Accerciser?action=show&redirect=Accerciser) would make it easier to debug this issue.

**Comment by negesti** [comment]
I will add an option to preferences to totally ignore the top panel (on primary screen). Not really neat but much easier than supporting all the extensions that hide the top panel.

**Comment by negesti** [comment]
Any feedback on the "always ignore top panel" option? can we close the issue?

**Comment by negesti** [comment]
closing as no response after quite some time
